@startuml
package "メール管理システム" {
    entity "ログインユーザ" as loginUser {
        + id(連番) [PK]
        ----
        userID
        UserName
        pass
    }
    entity "勤務地" as location{
        + locatitonID [PK]
        ---
        lovcationName
    }
    entity "メールアドレス" as maillAddress{
        + primaryAddressID[PK]
        ---
        address
        # registerID[FK]
        # syinID[FK]
    }
    entity "役職" as position{
        + positionID
        ---
        positionName
    }
    entity "社員情報" as syainInfo{
        + syainID
        ---
        syainName
        # locatinID[FK]
        # positionID[FK]
    }
    entity "登録進行状況" as statusRegiser{
        + statusRegisterID
        ---
        statusName
    }
    entity "登録情報" as regiseter{
        + registerID[PK]
        ----
        # userid(登録ユーザID)[FK]
        # statusRegisterID[FK]
        registerTime(タイムスタンプ)
        bikou(備考)
    }

    maillAddress |o--o{ syainInfo
    syainInfo |o--l-o{ position
    syainInfo |o-ri-o{ location
    regiseter |o-ri-o{ loginUser
    regiseter |o-l-o{ statusRegiser
    regiseter }o--o| maillAddress

}
@enduml